# Generated by Django 6.0.5 on 2026-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "full_name",
                    models.CharField(help_text="Введите полное имя сотрудника", max_length=255, verbose_name="ФИО"),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Введите должность сотрудника", max_length=255, verbose_name="Должность"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время последнего обновления")),
            ],
        ),
    ]
