# Generated by Django 6.0.5 on 2026-05-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название задачи", max_length=255, verbose_name="Наименование"),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Укажите дату выполнения задачи (ГГГГ-ММ-ДД)", verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("in_progress", "В работе"), ("done", "Выполнена")],
                        default="new",
                        help_text="Текущий статус выполнения задачи",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время последнего обновления")),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сотрудника, ответственного за задачу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="employees.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Задача, от которой зависит текущая",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
        ),
    ]
